[package]
name = "nexus"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true

clap = { version = "4.5.51", features = ["derive"] }
toml = "0.9.8"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

primitives = { path = "../../crates/primitives" }
tasks = { path = "../../crates/tasks" }
